# Generated by Django 5.2.3 on 2025-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('indistinto', 'Indistinto')], max_length=15)),
                ('tamaño', models.CharField(choices=[('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=15)),
                ('peso', models.FloatField()),
                ('estado_salud', models.TextField()),
                ('vacunado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=15)),
                ('temperamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('preferencias', models.JSONField(default=dict)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='sistema.perro')),
            ],
        ),
    ]
